// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ActionData struct {
	ID          string  `json:"ID"`
	Title       string  `json:"Title"`
	Description *string `json:"Description,omitempty"`
	Task        string  `json:"Task"`
	CreatedBy   *string `json:"CreatedBy,omitempty"`
	CreatedAt   *int    `json:"CreatedAt,omitempty"`
	UpdateAt    *int    `json:"UpdateAt,omitempty"`
}

type TaskData struct {
	ID          string        `json:"ID"`
	Title       string        `json:"Title"`
	Description *string       `json:"Description,omitempty"`
	Actions     []*ActionData `json:"Actions,omitempty"`
	CreatedBy   *string       `json:"CreatedBy,omitempty"`
	CreatedAt   *int          `json:"CreatedAt,omitempty"`
	UpdateAt    *int          `json:"UpdateAt,omitempty"`
}
