// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	Index        int    `json:"Index"`
	DisplayValue string `json:"DisplayValue"`
}

type Deck struct {
	ID    string  `json:"ID"`
	Name  string  `json:"Name"`
	Cards []*Card `json:"Cards"`
}
